import avatarBone from "../assets/global/jugadores/avatar1.png";
import avatarPacman from "../assets/global/jugadores/avatar2.png";
import avatarPlanta from "../assets/global/jugadores/avatar3.png";
import avatarGhost from "../assets/global/jugadores/avatar4.png";
import avatarShark from "../assets/global/jugadores/avatar5.png";
import avatarDog from "../assets/global/jugadores/avatar6.png";
import avatarInMove from "../assets/global/jugadores/avatarMove.mp4";
import avatarDraculaMan from "../assets/global/jugadores/draculaMan.png";
import avatarDraculaMan2 from "../assets/global/jugadores/draculaMan2.png";
import avatarDraculaWoman from "../assets/global/jugadores/draculaWoman.png";
import avatarDraculaWoman2 from "../assets/global/jugadores/draculaWoman2.png";
import avatarAlien from "../assets/global/jugadores/alienMove.mp4";
import Woman from "../assets/global/jugadores/woman.png";
import Man from "../assets/global/jugadores/Man.png";
import coins from "../assets/homeFirst/coins.png";
import energy from "../assets/homeFirst/energy.png";
import brocha from "../assets/homeFirst/brocha.png";
import DefaultAvatar from "../assets/global/jugadores/DefaultAvatar.png";


export const store = [
  {
    title: "500 XP",
    price: 20,
    description: "Add 500XP to the game you select",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: energy,
    image: true,
    category: "Consumable",
  },
  {
    title: "1000 XP",
    price: 50,
    description: "Add 1000XP to the game you select",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: energy,
    image: true,
    category: "Consumable",
  },
  {
    title: "2000 XP",
    price: 50,
    description: "Add 2000XP to the game you select",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: energy,
    image: true,
    category: "Consumable",
  },
  {
    title: "3000 XP",
    price: 50,
    description: "Add 3000XP to the game you select",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: energy,
    image: true,
    category: "Consumable",
  },
  {
    title: "50 Coins",
    price: 50,
    description: "add 50 coins ",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: coins,
    image: true,
    category: "Consumable",
  },
  {
    title: "100 Coins",
    price: 100,
    description: "add 100 coins",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: coins,
    image: true,
    category: "Consumable",
  },
  {
    title: "150 Coins",
    price: 150,
    description: "add 150 coins",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: coins,
    image: true,
    category: "Consumable",
  },
  {
    title: "200 Coins",
    price: 200,
    description: "add 200 coins",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: coins,
    image: true,
    category: "Consumable",
  },
  {
    title: "Rainbow Name",
    price: 100,
    description: "username",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: brocha,
    image: true,
    category: "Consumable",
  },
  {
    title: "Color specific",
    price: 100,
    description: "username",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: brocha,
    image: true,
    category: "Consumable",
  },
  {
    title: "Default Avatar",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: DefaultAvatar,
    image: true,
    category: "Avatar",
  },
  {
    title: "Bone",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarBone,
    image: true,
    category: "Avatar",
  },
  {
    title: "Pacman",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarPacman,
    image: true,
    category: "Avatar",
  },
  {
    title: "Plant",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarPlanta,
    image: true,
    category: "Avatar",
  },
  {
    title: "Ghost",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarGhost,
    image: true,
    category: "Avatar",
  },
  {
    title: "Shark",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarShark,
    image: true,
    category: "Avatar",
  },
  {
    title: "Dog",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarDog,
    image: true,
    category: "Avatar",
  },
  {
    title: "avatar In Move",
    price: 100,
    description: "dinamic avatar",
    levelNecesary: [{ levelB: 15, levelH: 20 }],
    url: avatarInMove,
    image: false,
    category: "Avatar",
  },
  {
    title: "Dracula Man",
    price: 75,
    description: "static avatar",
    levelNecesary: [{ levelB: 10, levelH: 12 }],
    url: avatarDraculaMan,
    image: true,
    category: "Avatar",
  },
  {
    title: "Dracula Man 2",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarDraculaMan2,
    image: true,
    category: "Avatar",
  },
  {
    title: "Dracula Woman",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarDraculaWoman,
    image: true,
    category: "Avatar",
  },
  {
    title: "Dracula Woman 2",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarDraculaWoman2,
    image: true,
    category: "Avatar",
  },
  {
    title: "Alien",
    price: 0,
    description: "dinamic avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: avatarAlien,
    image: false,
    category: "Avatar",
  },
  {
    title: "Woman",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: Woman,
    image: true,
    category: "Avatar",
  },
  {
    title: "Man",
    price: 0,
    description: "static avatar",
    levelNecesary: [{ levelB: 0, levelH: 0 }],
    url: Man,
    image: true,
    category: "Avatar",
  },
];
